### ISSUE TITLE
Wrong word in the Armenian version of the application

### ISSUE THREAD

**Issue by Narek1611** [MartirosSahakyan/Billiard_Club#9]
Dear Martiros, I was viewing your site and saw, that in the Armenian version of the site, in Navigation Menu you wrote Պատկերասրահ/a> instead of just Պատկերասրահ. Fix that bug, please.

**Comment by mrdosahakyan** [comment]
Dear Narek, you wrote just a same word: I can`t understand what you min

**Comment by mrdosahakyan** [comment]
Pls add comment directly on the code row that you mean.

**Comment by Narek1611** [comment]
Noo dear brother, you wrote "Պատկերասրահ/a>", you should write "Պատկերասրահ" , the "/a>" is excessive.

**Comment by Narek1611** [comment]
> Pls add comment directly on the code row that you mean.

I don't know how to do that.

**Comment by mrdosahakyan** [comment]
during next coffeetime I will show you that feature

**Comment by mrdosahakyan** [comment]
lets meet during 5 minutes next to water dipenser

**Comment by Narek1611** [comment]
I opened a pull request, you can accept.
But anyway let's meet in 5 minutes next to the water dispenser.

**Comment by mrdosahakyan** [comment]
Good Job!! I accept your pull request;
